RoomsProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('users.urls')),
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rooms/', views.allocation_list, name='rooms'),
]

core/models.py
from django.db import models

class User(models.Model):
    user_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=60)
    password = models.CharField(max_length=30)

    def __str__(self):
        return self.email

class Teacher(models.Model):
    teacher_id = models.AutoField(primary_key=True)
    siape = models.CharField(max_length=8)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class Discipline(models.Model):
    discipline_id = models.AutoField(primary_key=True)
    discipline_name = models.CharField(max_length=30)
    discipline_code = models.CharField(max_length=10)
    discipline_mode = models.BooleanField(default=False)
    discipline_course = models.CharField(max_length=30)

    def __str__(self):
        return self.discipline_name

class PhysicalSpace(models.Model):
    space_id = models.AutoField(primary_key=True)
    space_floor = models.IntegerField()
    space_number = models.IntegerField()
    space_block = models.CharField(max_length=1)
    space_type = models.BooleanField()

    def __str__(self):
        return f'{self.space_block} - {self.space_number}'



class Allocation(models.Model):
    DIAS_DA_SEMANA = [
        ('SEG', 'Segunda-feira'),
        ('TER', 'Terça-feira'),
        ('QUA', 'Quarta-feira'),
        ('QUI', 'Quinta-feira'),
        ('SEX', 'Sexta-feira'),
        ('SAB', 'Sábado'),
    ]
    HORARIOS = [
        ('08:00', '08:00 - 09:00'),
        ('09:00', '09:00 - 10:00'),
        ('10:00', '10:00 - 11:00'),
        ('11:00', '11:00 - 12:00'),
        ('12:00', '12:00 - 13:00'),
        ('13:00', '13:00 - 14:00'),
        ('14:00', '14:00 - 15:00'),
        ('15:00', '15:00 - 16:00'),
        ('16:00', '16:00 - 17:00'),
        ('17:00', '17:00 - 18:00'),
        ('18:00', '18:00 - 19:00'),
        ('19:00', '19:00 - 20:00'),
        ('20:00', '20:00 - 21:00'),
        ('21:00', '21:00 - 22:00'),
    ]

    allocation_id = models.AutoField(primary_key=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    discipline = models.ForeignKey(Discipline, on_delete=models.CASCADE)
    space = models.ForeignKey(PhysicalSpace, on_delete=models.SET_NULL, null=True, blank=True)
    days_week = models.CharField(max_length=3, choices=DIAS_DA_SEMANA)
    timetable = models.CharField(max_length=5, choices=HORARIOS)

    def __str__(self):
        return f'{self.teacher} - {self.discipline} - {self.space} - {self.timetable}'

templates/allocation_confirm_delete.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/delete.css' %}" />
    <title>Allocation Delete</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <header>
        <div class="logo">Rooms</div>
        <div class="login" id="back-button">Voltar</div>
    </header>
    <h1>Confirmação de Exclusão</h1>
    <p>Você tem certeza que deseja excluir a alocação de <br> {{ allocation.teacher }} - {{ allocation.discipline }} - {{ allocation.space }} - {{ allocation.get_days_week_display }} - {{ allocation.get_timetable_display }}?<br>Esta ação não é reversível!</p>
    <form method="post">
        {% csrf_token %}
        <button class="button" type="submit">Confirmar Exclusão</button>
    </form>
    <div class="alignA">
        <a class="return" href="{% url 'allocation_list' %}">Cancelar e voltar para a lista de alocações</a>
    </div>
    <script>
        $('#back-button').click(function(){
            window.history.back();
       });
    </script>
</body>
</html>

templates/allocation_form.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/form.css' %}" />
    <title>Allocation Form</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
<header>
    <div class="logo">Rooms</div>
    <div class="login" id="back-button">Voltar</div>
</header>
<h1>{% if allocation %}Editar Alocação{% else %}Adicionar Nova Alocação{% endif %}</h1>

<div class="errormid">
    {% if error %}
        <p style="color: red;">{{ error }}</p>
    {% endif %}
</div>

<form method="post">
    <div class="structureForm">
        <div class="formInformation">
            {% csrf_token %}
            {% if allocation %}
                <input type="hidden" name="allocation_id" value="{{ allocation.allocation_id }}">
            {% endif %}
            <label for="teacher">Professor:</label>
            <select id="teacher" name="teacher">
                {% for teacher in teachers %}
                    <option value="{{ teacher.pk }}" {% if allocation and allocation.teacher.pk == teacher.pk %}selected{% endif %}>{{ teacher }}</option>
                {% endfor %}
            </select><br><br>
            <label for="discipline">Disciplina:</label>
            <select id="discipline" name="discipline">
                {% for discipline in disciplines %}
                    <option value="{{ discipline.pk }}" {% if allocation and allocation.discipline.pk == discipline.pk %}selected{% endif %}>{{ discipline }}</option>
                {% endfor %}
            </select><br><br>
            <label for="space">Espaço:</label>
            <select id="space" name="space">
                {% for space in spaces %}
                    <option value="{{ space.pk }}" {% if allocation and allocation.space.pk == space.pk %}selected{% endif %}>{{ space }}</option>
                {% endfor %}
            </select><br><br>
            <label for="days_week">Dia da Semana:</label>
            <select id="days_week" name="days_week">
                {% for day_code, day_name in dias_da_semana %}
                    <option value="{{ day_code }}" {% if allocation and allocation.days_week == day_code %}selected{% endif %}>{{ day_name }}</option>
                {% endfor %}
            </select><br><br>
            <label for="timetable">Horário:</label>
            <select id="timetable" name="timetable">
                {% for time_code, time_name in horarios %}
                    <option value="{{ time_code }}" {% if allocation and allocation.timetable == time_code %}selected{% endif %}>{{ time_name }}</option>
                {% endfor %}
            </select><br><br>
        </div>
        <div class="divbutton">
            <button class="button" type="submit">{% if allocation %}Salvar{% else %}Adicionar{% endif %}</button>
        </div>
    </div>
</form>
<script>
        $('#back-button').click(function(){
            window.history.back();
       });
    </script>
</body>
</html>

templates/allocation_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/list.css' %}" />
    <title>Allocation List</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
<header>
    <div class="logo">Rooms</div>
    <div class="login" id="back-button">Voltar</div>
</header>
<h1>Lista de Alocações</h1>

<div class="search-container">
    <input type="text" id="search-input" placeholder="Buscar...">
</div>

<div class="contentList">
    <ul id="allocation-list">
        {% for allocation in allocations %}
            <li class="optionList">{{ allocation.teacher }} - {{ allocation.discipline }} - {{ allocation.space }} - {{ allocation.get_days_week_display }} - {{ allocation.get_timetable_display }}
                (<a class="options" href="{% url 'allocation_detail' pk=allocation.pk %}">Detalhes</a>)
                (<a class="options" href="{% url 'allocation_update' pk=allocation.pk %}">Editar</a>)
                (<a class="optionsE" href="{% url 'allocation_delete' pk=allocation.pk %}">Excluir</a>)
            </li>
            <br>
        {% empty %}
            <li>Nenhuma alocação encontrada.</li>
        {% endfor %}
    </ul>
</div>
<div class="alignA">
    <a class="return" href="{% url 'allocation_create' %}">Adicionar Nova Alocação</a>
    <br><br>
    <button class="return" id="generate-ensalamento-button">Gerar Ensalamento</button>
</div>
<script>
    $(document).ready(function(){
        $('#search-input').on('keyup', function() {
            var value = $(this).val().toLowerCase();
            $('#allocation-list .optionList').filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
            });
        });

        $('#generate-ensalamento-button').click(function(){
            $.ajax({
                url: '{% url "generate_ensalamento" %}',
                type: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                success: function(response) {
                    alert('Ensalamento gerado com sucesso!');
                    location.reload();
                },
                error: function(response) {
                    alert('Erro ao gerar ensalamento.');
                }
            });
        });
    });
    $('#back-button').click(function(){
         window.history.back();
    });
</script>
</body>
</html>

templates/discipline_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/details.css' %}" />
    <title>Discipline Detail</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <header>
        <div class="logo">Rooms</div>
        <div class="login" id="back-button">Voltar</div>
    </header>
    <h1>Detalhes da Disciplina</h1>
    <p><strong>Nome:</strong> {{ discipline.discipline_name }}</p>
    <p><strong>Código:</strong> {{ discipline.discipline_code }}</p>
    <p><strong>Curso:</strong> {{ discipline.discipline_course }}</p>
    <p><strong>Modo de Ensino:</strong> {% if discipline.discipline_mode %}Teórica/Prática{% else %}Teórica{% endif %}</p>
    <div class="options">
        <div class="optionA">
            <a class="optionAButton" href="{% url 'discipline_update' pk=discipline.pk %}">Editar</a>
            <a class="optionBButton" href="{% url 'discipline_delete' pk=discipline.pk %}">Excluir</a>
        </div>
        <div class="return">
            <a class="returnButton" href="{% url 'discipline_list' %}">Voltar para a lista de disciplinas</a>
        </div>
    </div>
    <script>
        $('#back-button').click(function(){
            window.history.back();
       });
    </script>
</body>
</html>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Oswald:wght@200..700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>Rooms</title>
</head>
<body>
    <header>
        <div class="logo">Rooms</div>
        <div class="login" onclick="location.href='{% url 'login' %}'">Administrador</div>
    </header>
    <main>
        <section class="apresentacao">
            <div class="opcoes">
                <div class="text">
                    <p class="slogan">Tecnologia a serviço do seu ensalamento</p>
                    <p class="subtitulo">Com esse sistema voce pode gerenciar melhor o ensalamento da sua instituição de ensino!</p>
                    <div class="buttonalign">
                        <button class="loginb" onclick="location.href='{% url 'login' %}'">Acessar como Administrador</button>
                        <button class="signup" onclick="location.href='{% url 'rooms' %}'">Acessar como Convidado</button>
                    </div>
                </div>
            </div>
            <div class="door">
                <img src="{% static 'imagens/portas.png' %}" alt="doors">
            </div>
        </section>
    </main>
</body>
</html>

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
    <title>Login</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <header>
        <div class="logo">Rooms</div>
        <div class="login" id="back-button">Voltar</div>
    </header>
    <h1>Login</h1>
    <div class="loginclass">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="buttonlogin" type="submit">Entrar</button>
            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            {% endif %}
        </form>
    </div>
<script>
        $('#back-button').click(function(){
            window.history.back();
       });
    </script>
</body>
</html>

templates/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Register</title>
</head>
<body>
    <header>
        <div class="logo">Rooms</div>
        <div class="login" id="back-button">Voltar</div>
    </header>
<h1>Registrar</h1>
<div class="errormid">
    {% if messages %}
    {% for message in messages %}
        <p style="color: red;">{{ message }}</p>
    {% endfor %}
{% endif %}
</div>
<form method="post">
    {% csrf_token %}
    <label for="username">Nome de usuário:</label>
    <input class="textclass" type="text" name="username" id="username" required><br>

    <label for="email">Email:</label>
    <input class="textclass" type="email" name="email" id="email" required><br>

    <label for="password">Senha:</label>
    <input class="textclass" type="password" name="password" id="password" required><br>

    <label for="password_confirm">Confirme a senha:</label>
    <input class="textclass" type="password" name="password_confirm" id="password_confirm" required><br>

    <button class="buttonlogin" type="submit">Registrar</button>
</form>
<script>
        $('#back-button').click(function(){
            window.history.back();
       });
</script>
</body>
</html>

templates/rooms.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Oswald:wght@200..700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/rooms.css' %}" />
    <title>Ensalamentos</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
<header>
    <div class="logo">Rooms</div>
    <div class="login" id="back-button">Voltar</div>
</header>
<h1 class="nome">Ensalamentos</h1>
<div class="buttonfiltros">
    <button class="downefilt1" id="download-button">Download</button>
    <button class="downefilt2" id="filter-button">Filtros</button>
</div>
<div class="filterclass" id="filter-section" style="display:none;">
    <form id="filter-form">
        <label for="course">Curso:</label>
        <select id="course" name="course">
            <option value="">Selecione um curso</option>
            {% for course in courses %}
                <option value="{{ course }}">{{ course }}</option>
            {% endfor %}
        </select>
        <button class="options" type="button" id="apply-filters">Aplicar Filtros</button>
    </form>
</div>
<div class="tabelaens">
    <table class="tabelastyle">
        <thead>
        <tr>
            <th>Professor</th>
            <th>Diciplina</th>
            <th>Sala</th>
            <th>Dia da Semana</th>
            <th>Horario</th>
        </tr>
        </thead>
        <tbody id="allocation-list">
        {% for allocation in allocations %}
            <tr>
                <td>{{ allocation.teacher }}</td>
                <td>{{ allocation.discipline }}</td>
                <td>{{ allocation.space }}</td>
                <td>{{ allocation.get_days_week_display }}</td>
                <td>{{ allocation.get_timetable_display }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<script>
    $(document).ready(function() {
        $('#filter-button').click(function() {
            $('#filter-section').toggle();
        });

        $('#apply-filters').click(function() {
            $.ajax({
                url: '{% url "allocation_list" %}',
                type: 'GET',
                data: $('#filter-form').serialize(),
                success: function(response) {
                    var tbody = $('#allocation-list');
                    tbody.empty();
                    response.allocations.forEach(function(allocation) {
                        var row = '<tr>' +
                            '<td>' + allocation.teacher + '</td>' +
                            '<td>' + allocation.discipline + '</td>' +
                            '<td>' + allocation.space + '</td>' +
                            '<td>' + allocation.days_week + '</td>' +
                            '<td>' + allocation.timetable + '</td>' +
                            '</tr>';
                        tbody.append(row);
                    });
                },
                error: function() {
                    alert('Erro ao aplicar filtros.');
                }
            });
        });

        $('#download-button').click(function() {
            var downloadUrl = '{% url "download_allocations_pdf" %}';
            window.location.href = downloadUrl;
        });

        $('#back-button').click(function() {
            window.history.back();
        });
    });
</script>
</body>
</html>

templates/space_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/details.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Space Detail</title>
</head>
<body>
    <header>
        <div class="logo">Rooms</div>
        <div class="login" id="back-button">Voltar</div>
    </header>
    <h1>Detalhes do Espaço Físico</h1>
    <p><strong>Andar:</strong> {{ space.space_floor }}</p>
    <p><strong>Número:</strong> {{ space.space_number }}</p>
    <p><strong>Bloco:</strong> {{ space.space_block }}</p>
    <p><strong>Tipo:</strong> {% if space.space_type %}Laboratório{% else %}Sala{% endif %}</p>
    <div class="options">
        <div class="optionA">
            <a class="optionAButton" href="{% url 'space_update' pk=space.pk %}">Editar</a>
            <a class="optionBButton" href="{% url 'space_delete' pk=space.pk %}">Excluir</a>
        </div>
        <div class="return">
            <a class="returnButton" href="{% url 'space_list' %}">Voltar para a lista de espaços físicos</a>
        </div>
    </div>
<script>
        $('#back-button').click(function(){
            window.history.back();
       });
    </script>
</body>
</html>

templates/space_form.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/form.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Space Form</title>
</head>

<body>
    <header>
        <div class="logo">Rooms</div>
        <div class="login" id="back-button">Voltar</div>
    </header>
    <h1>{% if space %}Editar Espaço Físico{% else %}Adicionar Novo Espaço Físico{% endif %}</h1>

    <div class="errormid">
        {% if error %}
        <p style="color: red;">{{ error }}</p>
        {% endif %}
    </div>

    <form method="post">
        <div class="structureForm">
            <div class="formInformation">
                {% csrf_token %}
                {% if space %}
                <input type="hidden" name="space_id" value="{{ space.space_id }}">
                {% endif %}
                <label for="space_floor">Andar:</label>
                <input type="number" class="textclass" id="space_floor" name="space_floor"
                    value="{% if space %}{{ space.space_floor }}{% endif %}"><br><br>

                <label for="space_number">Número:</label>
                <input type="number" class="textclass" id="space_number" name="space_number"
                    value="{% if space %}{{ space.space_number }}{% endif %}"><br><br>

                <label for="space_block">Bloco:</label>
                <input type="text" class="textclass" id="space_block" name="space_block" maxlength="1"
                    value="{% if space %}{{ space.space_block }}{% endif %}"><br><br>

                <label for="space_type">Tipo de Espaço:</label>
                <select id="space_type" name="space_type">
                    <option value="0" {% if space and not space.space_type %}selected{% endif %}>Sala</option>
                    <option value="1" {% if space and space.space_type %}selected{% endif %}>Laboratório</option>
                </select><br><br>
            </div>
            <div class="divbutton">
                <button class="button" type="submit">{% if space %}Salvar{% else %}Adicionar{% endif %}</button>
            </div>
        </div>
    </form>
    <script>
        $('#back-button').click(function () {
            window.history.back();
        });
    </script>
</body>

</html>

templates/teacher_confirm_delete.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/delete.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Teacher Delete</title>
</head>
<body>
    <header>
        <div class="logo">Rooms</div>
        <div class="login" id="back-button">Voltar</div>
    </header>
    <h1>Confirmação de Exclusão</h1>
    <p>Você tem certeza que deseja excluir o professor "{{ teacher.first_name }} {{ teacher.last_name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button class="button" type="submit">Confirmar Exclusão</button>
    </form>
    <div class="alignA">
        <a class="return" href="{% url 'teacher_list' %}">Cancelar e voltar para a lista de professores</a>
    </div>
<script>
        $('#back-button').click(function(){
            window.history.back();
       });
    </script>
</body>
</html>

templates/teacher_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/details.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Teacher Detail</title>
</head>
<body>
    <header>
        <div class="logo">Rooms</div>
        <div class="login" id="back-button">Voltar</div>
    </header>
    <h1>Detalhes do Professor</h1>
    <p><strong>Nome:</strong> {{ teacher.first_name }} {{ teacher.last_name }}</p>
    <p><strong>SIAPE:</strong> {{ teacher.siape }}</p>
    <div class="options">
        <div class="optionA">
            <a class="optionAButton" href="{% url 'teacher_update' pk=teacher.pk %}">Editar</a>
            <a class="optionBButton" href="{% url 'teacher_delete' pk=teacher.pk %}">Excluir</a>
        </div>
        <div class="return">
            <a class="returnButton" href="{% url 'teacher_list' %}">Voltar para a lista de professores</a>
        </div>
    </div>
<script>
        $('#back-button').click(function(){
            window.history.back();
       });
    </script>
</body>
</html>

templates/teacher_form.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/form.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>{% if teacher.pk %}Editar{% else %}Adicionar{% endif %} Professor</title>
</head>
<body>
    <header>
        <div class="logo">Rooms</div>
        <div class="login" id="back-button">Voltar</div>
    </header>
<h1>{% if teacher.pk %}Editar{% else %}Adicionar{% endif %} Professor</h1>
<div class="errormid">
    {% if error %}
    <p style="color: red;">{{ error }}</p>
    {% endif %}
</div>
<form method="post">
    <div class="structureForm">
        <div class="formInformation">
            {% csrf_token %}
            {% if teacher.pk %}
                <input type="hidden" name="teacher_id" value="{{ teacher.pk }}">
            {% endif %}
            <label for="siape">SIAPE:</label>
            <input class="textclass" type="text" id="siape" name="siape" value="{{ teacher.siape }}"><br><br>
            <label for="first_name">Nome:</label>
            <input class="textclass" type="text" id="first_name" name="first_name" value="{{ teacher.first_name }}"><br><br>
            <label for="last_name">Sobrenome:</label>
            <input class="textclass" type="text" id="last_name" name="last_name" value="{{ teacher.last_name }}"><br><br>

        </div>
        <div class="divbutton">
            <button class="button" type="submit">{% if teacher.pk %}Salvar{% else %}Adicionar{% endif %}</button>
        </div>
    </div>
</form>
<script>
        $('#back-button').click(function(){
            window.history.back();
       });
    </script>
</body>
</html>

templates/teacher_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/list.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Teacher</title>
</head>
<body>
    <header>
        <div class="logo">Rooms</div>
        <div class="login" id="back-button">Voltar</div>
    </header>
    <h1>Lista de Professores</h1>
    <div class="contentList">
        <ul>
            {% for teacher in teachers %}
                <li>{{ teacher.first_name }} {{ teacher.last_name }} - {{ teacher.siape }}
                    (<a class="options" href="{% url 'teacher_detail' pk=teacher.pk %}">Detalhes</a>)
                    (<a class="options" href="{% url 'teacher_update' pk=teacher.pk %}">Editar</a>)
                    (<a class="optionsE" href="{% url 'teacher_delete' pk=teacher.pk %}">Excluir</a>)
                </li>
            <br>
            {% empty %}
                <li>Nenhum professor encontrado.</li>
            {% endfor %}
        </ul>
    </div>
    <div class="alignA">
        <a class="return" href="{% url 'teacher_create' %}">Adicionar Novo Professor</a>
    </div>
<script>
        $('#back-button').click(function(){
            window.history.back();
       });
    </script>
</body>
</html>